# Sabotage Plugin
# All credits to Plugner
# Inspiration: McPvP and Gamemods.
config:
 # MIN = 3
 MIN_PLAYER_TO_START: 3
messages:
 JOIN_MESSAGE: 'Welcome to Sabotage!'
 FORCE_START: 'The game has been forced to start'
 FORCE_END: 'The game has been forced to end'
 GAME_ENDED: 'The game has ended!\nSaboteurs: '
 TITLE_STARTING: 'Sabotage'
 SUBTITLE_STARTING: 'Starting in ? seconds.'
 LOWER_THAN_MIN_PLAYER_COUNT: 'The Game was cancelled because does not have the minimum count of players.'
 PLAYER_DIE: 'You died.'
chest_itens:
 - '1:STONE'
 - '2:DIRT'
maps:
